language: android
os: windows
android:
  components:
    # The BuildTools version used by your project
    - build-tools-21.1.2

    # The SDK version used to compile your project
    - android-22
    
before_install: chmod +x gradlew 

notifications:
    email: false